### ISSUE TITLE
🐛 Event start time doesnt line up with stream

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#325] opened 2023-03-01 07:07 UTC
- Event start time = when doors open
- Live stream start time should be a separate field on the SharePoint list

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/38869720/222068115-6c3ffe48-c567-4062-b59c-08d662c0dd16.png">

**Comment by Calinator444** [comment] 2024-04-12 07:33
@wicksipedia 

cc: @bradystroud 

Discussing this with Brady. I'm not sure if the issue is still relevant. `Front Door open` and `Live Stream Start` already seem to be separate fields.

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/972873bc-337c-400b-bb76-6df4227446e0)

**Comment by Calinator444** [comment] 2024-04-17 02:58
I will investigate this tonight when the user group starts to see if the bug it still there.

**Comment by Calinator444** [comment] 2024-04-18 00:55
@wicksipedia 

The layout of the home page looks different to how it did in @bradystroud's screenshot but this issue seems to have already been fixed on main. I took the screenshot of the banner below on the day of the cloud-native user group and the start time on the website lined up with the time of the event. 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/3b4f3959-c4d9-458f-abb4-57d548560f17)

**Closed as completed** 2024-04-19 01:09 UTC
