### ISSUE TITLE
♻️Megamenu - Add The New Menu

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2115] opened 2024-02-01 05:10 UTC
Cc:

Hi @Harry-Ross 

### Pain
Currently the [SSW Website](https://www.ssw.com.au/) still uses an in-built component for the MegaMenu.
However, in https://github.com/SSWConsulting/SSW.Website/issues/1560, a separate Megamenu project has been created so that can it be exported as a package to be used on SSW Website. 
Link to Megamenu project: https://github.com/SSWConsulting/SSW.MegaMenu

### Tasks
```[tasklist]
### Tasks
- [x] Add v4.0.1 of the megamenu to SSW Website once it has been published to NPM
```

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/57d55b6e-bde4-4e21-bd59-56d8af117a95)
**Figure: The current in-built Megamenu on the SSW Website**

Thanks!

**Comment by amankumarrr** [comment] 2024-02-04 23:54
@Harry-Ross @jeoffreyfischer  

Hi @wicksipedia
 
It appears that the Megamenu npm package is causing issues specifically for Next.js projects. Even after testing it on a fresh Next.js project with `npm`, the error persists. Interestingly, it seems to work fine on other React projects

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/d4006b85-7a1f-42ae-8360-60552ab20d45)

**Figure: Error on loading the page** 

It seems that there is an issue with importing this module as an ES module:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/2ca8d72a-50b2-415f-876e-a0da18db4c31)

I've also tried adding these into `next.config.mjs` but it didn't fix the issue. 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/71385247/5afb08ef-0489-4614-9fde-1ecd5ed4af72)
**Figure: Next Config with transpile package and esmExternal settings**

**Comment by amankumarrr** [comment] 2024-02-05 23:32
@wicksipedia @christoment @jeoffreyfischer @Harry-Ross 

- locally built ssw.megamenu artifact and integrated it into our website and it worked fine without any issues. Encountered difficulties when attempting to install the package directly from the node package, the same issue persisted consistently.

- Tried running the installation with `yarn` instead of `pnpm`, but the issue persisted. Experimented with `npm` installation, but faced challenges due to the `jsx` module causing errors.

- Installed ssw.megamenu from npm package using `pnpm`. Copied the module from the 'node_modules' directory to the root directory. Reinstalled it using `pnpm add ./filePath` and it worked without any error. 


Upon investigation, it appears that the challenges encountered during the installation of the ssw.megamenu npm package may stem from a peer dependencies issue.

**Comment by amankumarrr** [comment] 2024-02-06 06:13
@jeoffreyfischer @wicksipedia @Harry-Ross 

It turned out to be an issue with Server Side Rendering (SSR) in NextJS. 

When the server ran locally, it attempted to call the Browser's API to fetch the Browser's URL from the backend. At that point, the browser wasn't loaded, and the react-use package wasn't available, causing the error.

Dynamic import with SSR turned off resolved this issue without any errors.

Thanks @christoment for helping out in debugging it locally.

**Comment by amankumarrr** [comment] 2024-02-07 23:52
@jeoffreyfischer @Harry-Ross @christoment 

Due to the slight delay caused by using dynamic import for ssw.megamenu and its impact on UX, and considering there's no straightforward way for complete client rendering using Page Routing, as discussed with @wicksipedia, we are contemplating migrating it to App Router. This change aims to avoid delays for client-side components, as it is affecting the carousel as well. 

I've tested it with App Router, and it appears to be working smoothly with the client component.

**Comment by wicksipedia** [comment] 2024-02-08 00:00
> Due to the slight delay caused by using dynamic import for ssw.megamenu and its impact on UX

as per my conversation with @UlyssesMaclaren - he agrees that the ux isn't up to scratch especially since google won't be able to index the menu

I'll have a look at whether we can incrementally adopt app router to solve the problem and re-advise

**Comment by wicksipedia** [comment] 2024-02-08 04:28
As per my conversation with @adamcogan - we can't go live with this ux and we want google to index the content of the megamenu.

Done - added task to upgrade to the new app router

**Comment by Harry-Ross** [comment] 2024-02-13 01:56
Hey @wicksipedia, just an FYI I investigated moving to the App Router back in July in https://github.com/SSWConsulting/SSW.Website/issues/1078, and found that we may encounter some issues with Tina.

Specifically, the use of the `useTina` hook - which powers Tina's visual editing needs the `"use client"` tag at the top of the file where it is used. This is problematic, as the hook is mostly used at the top level of pages to allow visual editing of most of the page, and means that we would be rendering entire pages with `"use client"`, meaning we wouldn't be able to reap the benefits of using RSC. 

As per https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#interleaving-server-and-client-components, you can't import a server component into a client component - meaning if we use `"use client"` at the top level of a page, we can't use server components within. 

If there's a way to still have visual editing functionality without using `useTina` this would solve the problem, but right now it doesn't seem that way - https://tina.io/docs/contextual-editing/react/. (Also Tina team member's recent message https://discord.com/channels/835168149439643678/835168149439643681/1197661180970414100). 

It also seems the Tina team have asked Vercel for a way to conditionally render client components (i.e. only use `useTina` when on the `/admin` route - similar to how it works with Astro) to no avail - https://github.com/vercel/next.js/discussions/43962

**Comment by wicksipedia** [comment] 2024-02-13 04:16
Ick... I hadn't gotten to that part of the comparison.
If you have a look at the PR environment, you'll see that the megamenu rendering is being deferred to the client -> doesn't look good on first load and can't be indexed by search engines.

Will it be easier to change the megamenu to make this work for now?
i.e. I think the useLocation hook is the reason that this has to be client rendered - we can swap this to a url prop that gets passed in

**Comment by Harry-Ross** [comment] 2024-02-13 04:22
> Will it be easier to change the megamenu to make this work for now? i.e. I think the useLocation hook is the reason that this has to be client rendered - we can swap this to a url prop that gets passed in

Yep, I think it will be easier, I've already played around with it a little bit and made some progress. Made an issue here: https://github.com/SSWConsulting/SSW.MegaMenu/issues/66. There's another way to import `useLocation` that doesn't throw errors in Next.

**Closed as completed** 2024-02-19 22:37 UTC
