### ISSUE TITLE
💚 PR check - Pagespeed insights fails on first run

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#785] opened 2023-06-11 07:17 UTC
The PageSpeed insights PR check fails on its first run.

I think this is because its needs the PR environment to be deployed, and there is a short period after the deploy has completed but 
the site is not actually live.

```[tasklist]
### Tasks
- [x] Investigate
- [x] Add a delay before running PageSpeed Insights
- [x] Follow-up with this PR https://github.com/wicksipedia/pagespeed-insights/pull/41, test it when it gets merged
```

![](https://github.com/SSWConsulting/SSW.Website/assets/38869720/d0f8d5b8-b784-4e07-b1f8-421fffa7b6fe)
**Figure: PageSpeed Insights failing**

**Comment by amankumarrr** [comment] 2023-06-16 00:51
@bradystroud @wicksipedia 

Hi Team,

After a thorough investigation, we have identified the root cause to be intermittent issues with URL accessibility with the actual GitHub flow.
To fix this issue I have introduced the following features to the flow.

### Features:
- **Improved Reliability**: To mitigate the intermittent URL accessibility issues, the workflow has been enhanced to make two additional attempts if the first attempt fails. This improves the overall reliability of the workflow.

- **Robust Flow**: In case of failure, the workflow has been modified to gracefully handle the situation without breaking the overall flow. This ensures smoother PR processing even when issues arise.

- **Enhanced Feedback**: To provide clearer feedback, error, and success messages have been enhanced with emojis. This visual representation makes it easier to identify the status of the workflow at a glance.

### Screenshot
<img width="387" alt="PageInsight Change" src="https://github.com/wicksipedia/pagespeed-insights/assets/71385247/90465d7e-2ade-46b2-89bc-dcaafe2389e9">

**Figure: Tested on your forked repo, showing error on the first instance, and ran successfully on the second attempt**

Here is its PR : https://github.com/wicksipedia/pagespeed-insights/pull/41

**Comment by amankumarrr** [comment] 2023-06-16 07:13
@bradystroud @wicksipedia 

This PR https://github.com/wicksipedia/pagespeed-insights/pull/41 has been merged with his main and I have tested it on our pipeline, seems like working fine now, therefore, I'm closing it.

**Closed as completed** 2023-06-19 07:13 UTC
