### ISSUE TITLE
📄 Re: SSW.Website - changing our Microsoft Partner badges

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#891] opened 2023-06-28 23:08 UTC
cc @hveraus 

Sent via email (same subject) by @chrisschultzssw :

As you have probably heard, Microsoft have changed their Cloud Partner Program. As of today, SSW has obtained the new **Data and AI** and **Digital & App Innovation** solution areas 🎉.
 
This means we have new badges that we should be using on our website, replacing the current Microsoft Gold Partner badges – e.g. in the sidebar here: https://www.ssw.com.au/ssw/Company/AboutUs.aspx

I have attached a new badge – let me know if you need other options.

![MicrosoftSolutionPartner](https://github.com/SSWConsulting/SSW.Website/assets/12601228/ac3fe41e-87cf-43c5-9eef-56d9051d511d)
 
We also need to change the wording – at a minimum, to change from **Microsoft Gold Certified Partner** to **Microsoft Solutions Partner**.
 
**Note:** @camillars  has asked the devs working on the new website about what will need to be changed there, as some content is being removed – I’ll create a PBI for this once we know more.
 
Could you please make these changes:
 
On our main page: https://www.ssw.com.au
1. Change the badge
2. Change the wording from:
 
> In 1999, we were first recognized as a Microsoft Gold Partner. Today SSW has competencies in a variety of areas, earning gold in Application Development, Application Integration, Cloud Platform, DevOps; and silver in Collaboration and Content, and Data Analytics.
 
To:
 
>  In 1999, we were first recognized as a Microsoft Gold Partner – now renamed Microsoft Cloud Partner. Today SSW has competencies in a variety of areas, including Data and AI and Digital & App Innovation.

**Comment by tiagov8** [comment] 2023-06-30 16:41
Hey @bradystroud 

I see this change live, but no 'Done'...

**Comment by bradystroud** [comment] 2023-07-03 22:32
Hey Tiago, this issue is a duplicate of #517

> Sent via email (same subject) by @chrisschultzssw :

I cant see this email in my inbox... Usually if there is an email I reply with a link to the issue.

Closing as duplicate

**Closed as not planned by bradystroud** 2023-07-03 22:32 UTC
