### ISSUE TITLE
🐛 MegaMenu - Update links to NextJs pages

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#424] opened 2023-03-16 06:48 UTC
cc @jontygardner @tkapa 

**Is your feature request related to a problem? Please describe.**
The MegaMenu links to the old website

**Describe the solution you'd like**

```[tasklist]
- [ ] Check with @wicksipedia then change the links to go to our shiny new website
```

**Comment by Harry-Ross** [comment] 2023-03-27 07:24
Closing as duplicate of #263

**Closed as not planned by Harry-Ross** 2023-03-27 07:24 UTC
