### ISSUE TITLE
✨ Office index page - Click to edit visual editing

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#842] opened 2023-06-20 02:00 UTC
Feature: https://tina.io/docs/contextual-editing/react/#click-to-edit-experimental
URL: https://ssw.com.au/offices
Route: `/offices`

#### Description:
Tina introduced a new exciting feature where user can edit the content by simply clicking on it, we need to implement this feature for our website and need to ensure that we follow this for our upcoming templates.

**Comment by bradystroud** [comment] 2023-07-05 22:18
This looks like a duplicate of https://github.com/SSWConsulting/SSW.Website/issues/835

@amankumarrr can you confirm?

**Comment by bradystroud** [comment] 2023-07-18 01:55
As discussed, we dont need this as there is no visual editor of the index because it is just JSON



![Image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/f99de0cc-a462-46bc-8f1e-e2417a61b4cc)
**Figure: No visual editor**

**Closed as not planned by bradystroud** 2023-07-18 01:55 UTC
