### ISSUE TITLE
✨ Newsletter - signup component

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#647] opened 2023-05-16 03:01 UTC
1. Get Power Automate endpoint deployed to prod
2. Finish newsletter signup component
3. Ensure newsletter signup component can be used in Tina editor

**Comment by amankumarrr** [comment] 2023-05-24 06:50
Closing this one as it is duplicate of this https://github.com/SSWConsulting/SSW.Website-v3/issues/682 issue.

**Closed as not planned by amankumarrr** 2023-05-24 06:50 UTC
